spring.application.name=backend

# PostgreSQL

spring.datasource.url=jdbc:postgresql://ep-empty-tree-analcvpz-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uLbAODnwJ16z
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080

# JWT
jwt.secret=b08e094dbd4713ee85a06e02adcd63ce1dae67bb6fe3aec0a916ef259484cd3d2e33a1744a1ff14bf1bb703715e5c1fe0e10db9381590e97a84972c99fc0f296
jwt.expiration=86400000

# OpenAI API Key — replace with your actual key from platform.openai.com
openai.api.key=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